# Generated by Django 4.2.3 on 2023-08-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('classification', models.DecimalField(decimal_places=0, max_digits=1)),
                ('species', models.DecimalField(decimal_places=0, max_digits=3)),
                ('is_mix', models.BooleanField()),
                ('gender', models.DecimalField(decimal_places=0, max_digits=1)),
                ('age', models.TextField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('haircolor', models.BinaryField(max_length=1)),
                ('filepath', models.TextField()),
                ('gu', models.DecimalField(decimal_places=0, max_digits=1)),
                ('locate', models.TextField()),
                ('rescue_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.DecimalField(decimal_places=0, max_digits=1)),
                ('name', models.TextField()),
                ('name_kr', models.TextField()),
            ],
        ),
    ]
